# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5fead0e8ca174eb7b92f87ddc5409b006a1c9f339814a75fbdeee1e6c8676208211f7f500583a327ce49d67937450b8346b0d432de42b555c66996d08a1f6e2

test:
  secret_key_base: c7a02c7f51e1f0828463c990d07b7b2c05bd08b46447c3c5444cb58ae401f84ac71e11d2b6cd7a1253ee6ce34060902fb12f8b78e7e8b9b594744b686b533f6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
